server:
  port: 12306
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&amp;useUnicode=true
    username: root
    password: 199211
    
    
  thymeleaf:
    cache: false
#    mode: HTML5
    
    
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml